apiVersion: v1
kind: Secret
metadata:
  name: mathsync-secret
  namespace: mathsync
type: Opaque
stringData:
  PORT: "5500"

  NODE_ENV: "production"
  FRONTEND_URL: ""

  DB_URI: "mongodb+srv://db_user:admin123@cluster0.5wv8ht1.mongodb.net/testing"

  JWT_SECRET: "secret"
  JWT_EXPIRATION: "1d"

  REFRESH_TOKEN_SECRET: "refresh_secret"
  REFRESH_TOKEN_EXPIRATION: "7d"

  ARCJET_KEY: "ajkey_01jwjyv2p7f22aenkvr40rcrsf"
  ARCJET_ENV: "production"

  CLOUDINARY_CLOUD_NAME: "del8molgi"
  CLOUDINARY_API_KEY: "881371996621387"
  CLOUDINARY_API_SECRET: "3yzXwGVzMhBQlSqegkUfglIvkzA"