apiVersion: v1
kind: Service
metadata:
  name: mathsync-service
  namespace: mathsync
  labels:
    app: mathsync-api

spec:
  type: LoadBalancer

  selector:
    app: mathsync-api

  ports:
    - name: http
      port: 80
      targetPort: 5500